[features]
seeds = false
skip-lint = false

[programs.devnet]
solagent = "FDBu2qdatZd7J1TiDTjCbzNtjqwuJi25UPY7qUdBBFNQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
